version: "3.7"

services:
  db:
    image: postgresfsa
    restart: always
    environment:
      POSTGRES_PASSWORD: password
#    ports:
#      - "5400:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
      depends_on:
        - db
      image: fullstackapp
      restart: always
      ports:
       - "5000:5000"
