---
resources:
  - name: fullstackapp
    type: git
    icon: github-circle
    source:
      uri: https://github.com/jjadeseravla/FullStackApp
  - name: fullstackapp-docker-image
    type: docker-image
    source:
      email: "jade.alvares@clearchannelint.com"
      username: "ccrocket"
      password: ((dhpassword))
      repository: ccrocket/fullstackapp

jobs:
  - name: fullstackapp
    public: true
    plan:
      - get: fullstackapp
        trigger: true
      - task: run-tests
        config:
          inputs:
            - name: fullstackapp
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: maven }
          run:
            dir: fullstackapp
            path: mvn
            args: ["test"]
      - put: fullstackapp-docker-image
        params:
          build: fullstackapp
